In [2]:
import numpy as np
from numpy import array

In [79]:
def find_nearest(array, searched, return_bool=False):
    """ Return the closest elements in array of 'searched' array.
    In case of multiple elements having equal difference with `searched` element, the one with least index is 
    returned. Also returns a boolean index
    
    Examples
    --------
    
    ::
        
        from numpy import array
        find_nearest(array([1,2,3,4]), array([2.1,2]))
        
        >>> (array([2, 2]), array([False, True, False, False], dtype=bool))
        
        find_nearest(np.array([1,2,3,4]), np.array([2.6,2]))
        
        >>> (array([3, 2]), array([False,  True,  True, False], dtype=bool))

    """

    b = np.zeros_like(array, dtype=bool)

    def find_nearest(array, value):
        idx = (np.abs(array - value)).argmin()
        return idx, array[idx]

    nearest_els = []
    try:
        for s in searched:
            idx, el = find_nearest(array, s)
            b[idx] = True
            nearest_els.append(el)
    except:
        idx, el = find_nearest(array, searched)
        b[idx] = True
        nearest_els.append(el)

    if return_bool:
        out = nearest_els, b
    else:
        out = nearest_els
    return out


In [80]:
l = np.array([5, 9, 12, 10, 20, 30, 1])

In [81]:
x = np.array([11,11,6,0,-1,50])

In [82]:
x = 22

In [83]:
find_nearest(l, x)

[20]

In [74]:
        find_nearest(np.array([1,2,3,4]), np.array([2.6,2]))


([3, 2], array([False,  True,  True, False]))

Changes in this version and original:
1. if multiple elements in the searched array have identical answers, they are repeated as many times for each element in the output list.
2. the index of elements in the output list equal the index of element they are nearest to in the input list
3. return argmax as it served no purpose

Also removed shift_array function

In [87]:
l = np.arange(10)

In [88]:
l

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [89]:
find_nearest(l,l)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [93]:
x1 = array([1,1,1,1,1,1])
y1 = array([1,2,3,4,5,6])
find_nearest(x1, y1)

[1, 1, 1, 1, 1, 1]

In [96]:
x1 = array([0,1,2,3,4,5,6,7])
y1 = array([7,6,5,4,3,2,1,0])
find_nearest(x1,y1)

[7, 6, 5, 4, 3, 2, 1, 0]

In [95]:
x1 = array([1.5, 2.0, 2.5, 3.0])
y1 = array([-10, 10, 2.25])
find_nearest(x1, y1)

[1.5, 3.0, 2.0]

In [100]:
from radis import SpectrumFactory

In [4]:
def test_find_nearest(*args, **kwargs):
    a = np.arange(10)
    b = np.ones_like(a)
    assert (find_nearest(a, a) == a).all()
    assert (find_nearest(a, b) == b).all()
    assert (find_nearest(a, a[::-1]) == a[::-1]).all()
    assert (
        find_nearest(
            np.array([1.5, 2.0, 2.5, 3.0]),
            np.array([-10, 10, 2.25]) == np.array([1.5, 3.0, 2.0]),
        )
    ).all()
    assert find_nearest(np.array([10]), np.array([-10, 0, 10])) == np.array([0, 0, 0])


In [12]:
assert (np.array([1,2,3]) == np.array([1,2,3,4])).all()

/home/pankaj/anaconda3/envs/radis-dev/lib/python3.6/site-packages/ipykernel_launcher.py:1: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  """Entry point for launching an IPython kernel.


AttributeError: 'bool' object has no attribute 'all'

In [6]:
a = np.arange(10)
b = np.ones_like(a)

x, y = find_nearest(a, a, True)
assert (x == a).all()

In [13]:
x, y= find_nearest(a,a)

ValueError: too many values to unpack (expected 2)

In [31]:
def test_find_nearest(*args, **kwargs):
    a = np.arange(10)
    b = np.ones(5)
    #print("b = ", b)
    x1, y1 = find_nearest(a, a, True)
    assert (x1 == a).all()
    assert (len(y1) == len(a))
    assert (y1 == np.array([True for i in a])).all()

    x2, y2 = find_nearest(a, b, True)
    print("y2 = ", y2)
    assert (x2 == b).all()
    assert (len(x2) == len(b))
    assert (len(y2) == len(a))
    assert (y2 == np.array([i==1 for i in a])).all()

    assert (find_nearest(a, a[::-1]) == a[::-1]).all()
    assert (find_nearest(np.array([1.5, 2.0, 2.5, 3.0]),np.array([-10, 10, 2.25])) == np.array([1.5, 3.0, 2.0])).all()

    x3, y3 = find_nearest(np.array([10]), np.array([-10, 0, 10]), True)
    assert (x3 == np.array([10, 10, 10])).all()
    assert (len(y3) == 1)
    assert (y3 == [True])

In [32]:
test_find_nearest()

y2 =  [False  True False False False False False False False False]


In [1]:
def find_nearest(array, searched, return_bool=False):
    """ Return the closest elements in array for each element in 'searched' array.
    In case of multiple elements in `array` having equal difference with
    `searched` element, one with least index is returned. Also returns a boolean
    array with indices of elements occuring in output list set to true.

    Examples
    --------

    ::

        from numpy import array
        find_nearest(array([1,2,3,4]), array([2.1,2]))

        >>> (array([2, 2]), array([False, True, False, False], dtype=bool))

        find_nearest(np.array([1,2,3,4]), np.array([2.6,2]))

        >>> (array([3, 2]), array([False,  True,  True, False], dtype=bool))

    """
    if len(array) == 0:
        raise ValueError("Array to be searched cannot be empty")

    b = np.zeros_like(array, dtype=bool)

    def find_nearest(array, value):
        idx = (np.abs(array - value)).argmin()
        return idx, array[idx]

    nearest_els = []
    try:
        for s in searched:
            idx, el = find_nearest(array, s)
            b[idx] = True
            nearest_els.append(el)
    except:
        idx, el = find_nearest(array, searched)
        b[idx] = True
        nearest_els.append(el)

    if return_bool:
        out = nearest_els, b
    else:
        out = nearest_els

    return out

In [7]:
find_nearest(array([]), array([]), True)

ValueError: Array to be searched cannot be empty

In [6]:
assert (np.array([])==np.array([])).all()

In [8]:
a = np.arange(10)
b = np.ones(5)

x1, y1 = find_nearest(a, a, True)
assert (x1 == a).all()
assert len(y1) == len(a)
assert (y1 == np.array([True for i in a])).all()

x2, y2 = find_nearest(a, b, True)
assert (x2 == b).all()
assert len(x2) == len(b)
assert len(y2) == len(a)
assert (y2 == np.array([i == 1 for i in a])).all()

x3, y3 = find_nearest(np.array([10]), np.array([-10, 0, 10]), True)
assert (x3 == np.array([10, 10, 10])).all()
assert len(y3) == 1
assert y3 == [True]

x4, y4 = find_nearest(np.array([1, 4, 3]), np.array([]), True)
assert (x4 == np.array([])).all()
assert (len(y4) == 3)
assert (y4 == [False for _ in range(3)]).all()

assert (find_nearest(a, a[::-1]) == a[::-1]).all()
assert (
    find_nearest(np.array([1.5, 2.0, 2.5, 3.0]), np.array([-10, 10, 2.25]))
    == np.array([1.5, 3.0, 2.0])
).all()

assert (find_nearest(np.array([1, 3]), np.array([2])) == np.array([1])).all()
assert (find_nearest(np.array([3, 1]), np.array([2])) == np.array([3])).all()